// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC62MMULSXFL7x0bvJzSxrRhA9Th92eqrs',
    appId: '1:604097997429:web:290b40d8e2eae5eee3663c',
    messagingSenderId: '604097997429',
    projectId: 'task-management-74e69',
    authDomain: 'task-management-74e69.firebaseapp.com',
    storageBucket: 'task-management-74e69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh14ejLrNvXERxxbpMBMvEJSj6Of0N4Cc',
    appId: '1:604097997429:android:1ebeb6fcae98f885e3663c',
    messagingSenderId: '604097997429',
    projectId: 'task-management-74e69',
    storageBucket: 'task-management-74e69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2qDvbTBb_bwBe0-zoPFwxfwAM03kfC4',
    appId: '1:604097997429:ios:a8b1a85191f91a76e3663c',
    messagingSenderId: '604097997429',
    projectId: 'task-management-74e69',
    storageBucket: 'task-management-74e69.appspot.com',
    iosClientId: '604097997429-fbg7ajaoea1krbo0vmbt70efl6svci21.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2qDvbTBb_bwBe0-zoPFwxfwAM03kfC4',
    appId: '1:604097997429:ios:a8b1a85191f91a76e3663c',
    messagingSenderId: '604097997429',
    projectId: 'task-management-74e69',
    storageBucket: 'task-management-74e69.appspot.com',
    iosClientId: '604097997429-fbg7ajaoea1krbo0vmbt70efl6svci21.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );
}
